// GENERATED by scripts/seed-local.mjs against chain 11155111. Re-run the seed to regenerate.
// Restore the placeholder/mainnet values before shipping a mainnet build.
export const config = {
  chainId: 11155111,

  // Reads go through the connected wallet. A local node can also answer directly, which is handy
  // before a wallet is connected; on any public chain this stays empty, so the app ships no endpoint
  // of its own and a sandboxed ERC-8244 client has nothing to block.
  rpcUrl: "",

  // Freshly deployed local contracts:
  rock: "0xd1fc41c094065f22eea5e2769821efad792eff5b",
  market: "0xc5da5eba0fe69150649a54413d463bffad3e14f2",

  // Mocks standing in for EtherRock v1 and the two old wrappers. On mainnet these are the real
  // 2017 contracts (addresses at the bottom); anywhere else they have to be deployed, because
  // there is no EtherRock on a testnet to wrap.
  v1: "0x48d1a80c56fe2da586031979bb1e9e7d53fe8c01",
  wrapperSub100: "0xe6b54cc74cda1cf2b70d30bcc7eab22cf3dd6b22",
  wrapper10k: "0x63798c60c16a7c14919292738f2bfa8c7fa6c66b",

  // Gwei Name Service, here a local MockGNS with names staged by the seed. Set this to zero to
  // check the no-name path: lookups are skipped entirely and every address renders raw.
  gns: "0xb6fb4a1089a9d994f661c2b5e12014bdf2d2d373",

  // The block EthereumRock was deployed in. The Account page's "your rocks" scan reads ERC-721
  // Transfer logs, and public RPCs cap eth_getLogs at ~10k blocks per query, so the scan starts here
  // and pages forward instead of from genesis. Wrong-but-earlier is safe (just slower); later than
  // the first wrap would MISS rocks, so keep it <= the deploy block.
  deployBlock: 11348457,

  maxId: 10000,
};

// Canonical MAINNET addresses (restore these for a real deploy):
//   v1:            0x37504AE0282f5f334ED29b4548646f887977b7cC
//   wrapperSub100: 0xb895cAffECb62B5E49828c9d64116Fd07Dd33DEF
//   wrapper10k:    0x39b780E8062CE299ab60ed3D48F447e97511a2eD
//   gns:           0x9D51D507BC7264d4fE8Ad1cf7Fe191933A0a81d6  (Gwei Name Service)
